language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-milagro' ]; then cd .. && eval "mv $currentfolder generator-milagro" && cd generator-milagro; fi

